.PHONY: typeset

typeset:
	pandoc                          \
	  --from         markdown       \
	  --to           latex          \
	  --template     template.tex   \
	  --out          Assignment2Report.pdf \
	  --latex-engine   xelatex        \
	  Assignment2Report.md
