.PHONY: typeset

typeset:
	pandoc                          \
	  --from         markdown       \
	  --to           latex          \
	  --template     template.tex   \
	  --out          Assignment1Report.tex \
	  --latex-engine   xelatex        \
	  Assignment1Report.md
